---
title: "Newey-West HAC errors for OLS"
author: "Nayef Ahmad"
date: "2022-03-08" 
output: 
   github_document: 
     toc: true
     number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview 

Reference: 

- [Cross Validated - OLS regression with Newey-West error term](https://stats.stackexchange.com/a/254596/56828)


# Libraries 

```{r}
library(lmtest)
library(sandwich)

```


# Example 1: White noise error (base case)

```{r}
n <- 50
slope <- .05


white_noise_residuals <- rnorm(n)
x <- 1:n
y <- slope*(x) + white_noise_residuals

fit <- lm(y~x)

par(mfrow = c(1,3))
plot(x,y)
abline(fit, col = 'blue')
acf(fit$residuals)
pacf(fit$residuals)


summary(fit) # standard estimates
coeftest(fit, vcov = NeweyWest(fit, verbose = T))
```


# Example 2: Autocorrelated error 

```{r}
n <- 50
slope <- .05


correlated_residuals <- arima.sim(list(ar = .9), n)
x <- 1:n
y <- slope*(x) + correlated_residuals

fit <- lm(y~x)

par(mfrow = c(1,3))
plot(x,y)
abline(fit, col = 'blue')
acf(fit$residuals)
pacf(fit$residuals)


summary(fit) # standard estimates
coeftest(fit, vcov = NeweyWest(fit, verbose = T))
```

# Example 3: Pure ARIMA series as dependent variable 

```{r}
n <- 50
slope <- .05


y <- arima.sim(list(ar = .9), n)
x <- 1:n

fit <- lm(y~x)

par(mfrow = c(1,3))
plot(x,y)
abline(fit, col = 'blue')
acf(fit$residuals)
pacf(fit$residuals)

summary(fit) # standard estimates
coeftest(fit, vcov = NeweyWest(fit, verbose = T))
```

